services:
  postgres:
    image: ankane/pgvector:latest
    container_name: chatbot_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vector-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d vector-db"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: .
    container_name: chatbot_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
    name: chatbot_pg_data